name: ESX 1.8.5 Setup
description: Telepíti az ESX 1.8.5 verziót és a szükséges kiegészítőket.
author: TeNeved

tasks:
  - task: download
    input:
      source: "https://github.com/esx-framework/esx-legacy/archive/refs/tags/v1.8.5.zip"
      destination: "resources/[esx]/es_extended"

  - task: download
    input:
      source: "https://github.com/esx-framework/esx_menu_default/archive/refs/heads/main.zip"
      destination: "resources/[esx]/esx_menu_default"

  - task: download
    input:
      source: "https://github.com/esx-framework/esx_menu_list/archive/refs/heads/main.zip"
      destination: "resources/[esx]/esx_menu_list"

  - task: download
    input:
      source: "https://github.com/esx-framework/esx_menu_dialog/archive/refs/heads/main.zip"
      destination: "resources/[esx]/esx_menu_dialog"

  - task: download
    input:
      source: "https://github.com/citizenfx/cfx-server-data/archive/refs/heads/master.zip"
      destination: "resources/[system]/essentialmode"

  - task: file_append
    input:
      file: "server.cfg"
      content: |
        ensure es_extended
        ensure esx_menu_default
        ensure esx_menu_list
        ensure esx_menu_dialog

  - task: run_sql
    input:
      source: "https://github.com/esx-framework/esx-legacy/raw/v1.8.5/sql/extended.sql"
